### ISSUE TITLE
Other mods not compatible

### ISSUE THREAD

**Issue by barry1911** [gurrgur/er-patcher#15]
Hi,

I really like your mod and use most of the features it provides.
I would also like to use https://github.com/soupstream/EldenRingStutterFix , but it doesn't work when i start the game with ER-Patcher.
Is there a way i can use this while also using ER-Patcher?
Or any chance of adding this to ER-Patcher?

Thanks in advance

**Comment by Ryusennin** [comment]
It's a d3d12.dll replacement lib.

Personally, I copy that dll in the **_er-patcher-tmp_** folder and modify your Python script to comment the last line (os.rmdir) so that the temp folder is not deleted after every game session. A bit of a kludge, but it does work.

**Comment by barry1911** [comment]
> It's a d3d12.dll replacement lib.
> 
> Personally, I copy that dll in the **_er-patcher-tmp_** folder and modify your Python script to comment the last line (os.rmdir) so that the temp folder is not deleted after every game session. A bit of a kludge, but it does work.

mind telling me how you did it exactly? i don't know much about programming unfortunately.

**Comment by Ryusennin** [comment]
Basically, ER-Patcher creates a temporary folder named "er-patcher-tmp" in the main "ELDEN RING/Game" folder. In order to bypass EAC, it makes a copy of the program eldenring.exe in this folder and apply its patches on this copy without modifying the original exe. When you quit the game, ER-Patcher removes the temporary folder and the modified exe.

Problem is, the stutter fix needs to put its own library (d3d12.dll) in the same folder as eldenring.exe. You probably copied that dll into the base folder, which means this will not work with the modified exe. You need to edit ER-Patcher's script so that the temp folder in which the modified exe resides is not deleted after each game session.

1. Create a folder named "er-patcher-tmp" in "ELDEN RING/Game".
2. Copy the d3d12.dll from EldenRingStutterFix into "ELDEN RING/Base/er-patcher-tmp".
3. Open the script "er-patcher" (which you must have installed in "ELDEN RING/Game") with a text editor like Notepad.
4. Change the last line "os.rmdir(patched_exe_dir)" to "# os.rmdir(patched_exe_dir)" (ie. add a hash sign in front of that line to disable it).
5. Save the script as is (dont' change its name, location or format).

Hope it helps!

**Comment by barry1911** [comment]
It worked. Thank you very much for the in depth explanation.

**Comment by gurrgur** [comment]
Reopening since I think there might be a fix for this which could also fix #3. My idea is to link all files and directories from the game directory (except start_protected_game.exe and the unmodified eldenring.exe) to `er-patcher-tmp`. The working directory will have to be set to `er-patcher-tmp`, too. This should in theory fix all relative path and dll loading related bugs.

**Comment by gurrgur** [comment]
Can you please test if this attached version of [er-patcher](https://github.com/gurrgur/er-patcher/files/8353264/er-patcher.zip) works with the mod? Please also remove `er-patcher-tmp` beforehand if you get around to it.

**Comment by Ryusennin** [comment]
I did a quick test and the hardlinks seem to run fine. I even tried loading a few mods through ASI Loader without any issue.

Great work!

**Comment by barry1911** [comment]
I also just tried it with https://www.nexusmods.com/eldenring/mods/117 which you can utilize to use multiple mods. And it also worked like a charm.
Thanks!

**Comment by Ryusennin** [comment]
The hardlinks are virtual files (like shortcuts). The script can't possibly copy 50 GB of data in one second ;)

**Comment by gurrgur** [comment]
Yes we don't copy any files. When we create a hard link to a file, we just get an an additional reference to the same underlying data. The file system tracks the number of references (hard links) to that underlying data and only deletes the data when the number of references becomes zero.

If we were to delete the hard link we created, the original file and it's underlying data remains untouched. On the other hand, if we were to delete the original files, the hard links we created as well as the data they point to would remain untouched.
Therefore the underlying data only gets deleted when both original files and the links we created are deleted.

On another note, I've pushed the changes for better mod support so I'll be closing this issue :)
