### ISSUE TITLE
Not working for some reason?

### ISSUE THREAD

**Issue by DoomSlinger** [gurrgur/er-patcher#17]
I was trying to play ER with this patch, I put this in the launch options command line "./er-patcher --rate 360 -u -- %command%"
Ultra wide works (though I use it for a 4:3 monitor) but the rate comand isn't working, unless i limit the fps below 30. I tried an older version and it didn't fix it (maybe I need to go back further). I'm using an nvidia gpu if that could affect it at all.

**Comment by gurrgur** [comment]
It seems to be working though?

The issue seems to be with your setup

- the gpu may be incapable of pushing out more than 30 fps
- there bight be a frame rate limit set somewhere outside er-patcher (in the driver perhaps?)

**Comment by DoomSlinger** [comment]
I know the gpu can output more than 30 fps (int runs at 60 if I don't specificly limit it to 30 with your mod) but it doesn't go above 60. It can go above 60 when I play in windows and use the patches there, so I guess there is a driver issue? I tested some other games though and they were fine going over 60 fps as long as Vsync was disabled. (including proton games) but the monitor I'm playing on has a refresh rate higher than 60 so it can't be a vsync issue otherwise it would be running higher.

**Comment by gurrgur** [comment]
Okay, I'll need some more information:

- Which OS are you using? If linux, which desktop environment? It sounds like you are using both linux and windows and the issue only occurs on linux?
- What game version are you on?
- Which launch options did you use when the framerate unlock did not work?
- Did you try a 45fps limit? If that works as expected, I think vsync might be causing it. Have you checked that the monitor is actually set to a higher than 60Hz rate? Some monitors default to 60.

**Comment by DoomSlinger** [comment]
Ok, I did some testing, and I'm wondering if steam overly just isn't showing the higher frame rate for this game. I just looked at a few other DS games (DS remastered specificly) and it has the exact same issue. It says it's running at 60 fps in the overly, even though the game settings are showing it set to the higher refresh rate. In fact, I went to another resolution that can run at a higher refresh rate on this monitor (and is natively supported by it, unlike the refresh rate I was using) and that also showed as being stuck at 60... HOWEVER, I could tell that the game was WAY smoother than it would be if it was running at 60 fps like steam overlay says it is. I'll grab another fps counter and see if it detects it properly.

To answer the questions provided though, I'm using KDE-plasma on arch, Should be latest game version (it's a fresh install of the game), the launch options I use are ./er-patcher --rate 360 -u -- %command% (all settings for --rate above 60 don't seem to work, I've tried several), 45 does work.

**Comment by gurrgur** [comment]
Thanks for the info. Though DS Remastered is a bad benchmark for >60fps since it is actually locked to 60. The game lets you choose higher refresh rates but it still renders at most 60 frames per second.

For monitoring fps and other stats I recommend [mangohud](https://github.com/flightlessmango/MangoHud). It's available on AUR and it's pretty much the best game performance overlay there is on linux.
Besides monitoring fps you can also use it to force a specific vsync mode. Try forcing vsync off and see if it helps getting past 60fps.
Use this command:

> `./er-patcher --rate 360 -uvca -- env MANGOHUD=1 MANGOHUD_CONFIG=full,vsync=1 %command%`

You might have to log out or reboot for mangohud to work.

Anyway I'm positive that this is an issue with your setup and not with our little patcher script, so I'll be closing this issue. Try reddit if more tech support is necessary. Also, the arch wiki might be helpful for nvidia driver related issues.

**Comment by DoomSlinger** [comment]
Hey, I just tested it with mango hud, and it definatly is still running at 60 fps
