### ISSUE TITLE
FPS Uncap not working

### ISSUE THREAD

**Issue by DoomSlinger** [gurrgur/er-patcher#18]
Hey, you closed the issue before I actually got to test with mango hud, The issue is definatly not steam overly. Mango also found it to be 60 fps. I'm kinda stumped on this one because no other game, other than the DS games, seem to be having this issue.

**Comment by gurrgur** [comment]
Hi, I closed the other issue because I am convinced that this is not caused by `er-patcher`. Most likely something else on your system is limiting the framerate to 60 since the fps limit patch evidently works for values smaller than 60.

The only hint I can give is to try the `-f` flag or run in windowed mode. Maybe try disabling the "ForceCompositionPipeline" setting in nvidia control panel. If you are using a laptop, this might be PRIME related.

However I cannot and will not provide further system setup related tech support. We can leave this issue open in case I am wrong and this really is an issue caused by `er-patcher`. And maybe someone else recognizes your problem and provides a solution.

**Comment by DoomSlinger** [comment]
Ok, I have determined it's vsync. I have a multimonitor setup and I read somewhere that linux has issues with vsync (at least on nvidia) where it uses lowest refresh rate monitor to vsync too even if it isn't displaying on that monitor. I just need to figure out how to turn off vsync and it should work. Sorry for the trouble. I'll look into it
