### ISSUE TITLE
Not working on Win11 + 1.10 game version

### ISSUE THREAD

**Issue by NostromoUS** [gurrgur/er-patcher#55]
Hopefully someone sees this! 

I first tried with python 3.12 directly from their website and nothing happened, uninstalled then tried with the Store version and now it does open python console, then closes it and the game never starts. I tried everything I thought of, including "unblocking" the er-patcher file as Windows for some reason "blocks it" as it's probably not signed / recognized. 

Any ideas? Anything I can edit in the file to make it work? I can see the temp folder is created and populated btw. If I try to run the eldenring.exe in there it just says a ton of dlls arent installed such as oo2core etc

I've tried: 

`python er-patcher --rate 120 --disable-vigniette --disable-ca --skip-intro --remove-60hz-fullscreen --disable-rune-loss -- %command%`

and even simpler

`python er-patcher --rate 120 --all --disable-rune-loss -- %command%`

Thanks!

**Comment by gurrgur** [comment]
Has it ever worked for you on a previous version of the game or windows? 1.10 should be working fine so I guess its something with your setup.

Since the console window opens and the temp folder is created, the patcher script runs as intended, so no "blocking" by windows.

You can try `python er-patcher -- %command%` to see whether this is caused by any of the patches. Other than that I dont know what the problem could be. Dont have windows 11 either, so I cant test it on that.

**Comment by mtnorthcott** [comment]
To fix this on Windows 11, you can change L137 to
```python
(game_dir_patched / f).hardlink_to(f)
```

**Comment by gurrgur** [comment]
Oh, ok. It seems then the core issue at play is that python 3.12 finally removed the `link_to` method.

**Comment by gurrgur** [comment]
@NostromoUS Can you please test this change and report back whether it solves your issue?

You can get the updated version here: https://github.com/gurrgur/er-patcher/tree/python-3-12-compat

Also thanks @mtnorthcott for the fix.
